### ISSUE TITLE
Stuck after 2550 removals

### ISSUE THREAD

**Issue by ghost** [tripflex/wp-job-manager-empty-meta-cleanup#3]
Hi there,

I tried to remove a lot of empty meta data (558k empty entries) but I always get an error:

"Maximum call stack size exceeded"

And then the counter stucks at: "Removing 2550 of 529221 Meta Entries..."

I can restart the cleaner and start it again and another 2550 entries are deleted until it stucks.

Tried it with different browsers.

Do you have an idea why this occurs?

**Comment by tripflex** [comment]
I suggest opening a support ticket as the existing meta removal is a feature only available with integration of paid plugins
